query: PRAGMA foreign_keys = OFF
query: BEGIN TRANSACTION
query: SELECT * FROM "sqlite_master" WHERE "type" = 'table' AND "name" IN ('node','ir_device','aircon_device_status','ami_status','ir_type_model')
query: SELECT * FROM "sqlite_master" WHERE "type" = 'index' AND "tbl_name" IN ('node','ir_device','aircon_device_status','ami_status','ir_type_model')
query: SELECT * FROM "sqlite_master" WHERE "type" = 'table' AND "name" = 'typeorm_metadata'
query: CREATE TABLE "node" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL)
query: CREATE TABLE "ir_device" ("createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "nodeId" integer, "readerDeviceId" integer, "irTypeId" integer, CONSTRAINT "REL_f41f602cc3f82ae81002343601" UNIQUE ("readerDeviceId"))
query: CREATE TABLE "aircon_device_status" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "readerDeviceId" integer, "irDeviceId" integer, "tempCurrenttemperature" integer NOT NULL, "tempSettingtemperature" integer NOT NULL, CONSTRAINT "REL_6a70d5a7ea294ba7efa5ae326d" UNIQUE ("readerDeviceId"), CONSTRAINT "REL_c90ce7ba2ccd5df5a8fd2b2dab" UNIQUE ("irDeviceId"))
query: CREATE TABLE "ami_status" ("createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "nodeId" integer, "channel1NameChannelname1" varchar NOT NULL, "channel1NameChannelname2" varchar NOT NULL, "channel1NameChannelname3" varchar NOT NULL, "channel1WattWatt1" integer NOT NULL, "channel1WattWatt2" integer NOT NULL, "channel1WattWatt3" integer NOT NULL, "channel1WattHourWatthour1" integer NOT NULL, "channel1WattHourWatthour2" integer NOT NULL, "channel1WattHourWatthour3" integer NOT NULL, "channel2NameChannelname1" varchar NOT NULL, "channel2NameChannelname2" varchar NOT NULL, "channel2NameChannelname3" varchar NOT NULL, "channel2WattWatt1" integer NOT NULL, "channel2WattWatt2" integer NOT NULL, "channel2WattWatt3" integer NOT NULL, "channel2WattHourWatthour1" integer NOT NULL, "channel2WattHourWatthour2" integer NOT NULL, "channel2WattHourWatthour3" integer NOT NULL, CONSTRAINT "REL_311f085e405c61b6ef447407cf" UNIQUE ("nodeId"))
query: CREATE TABLE "ir_type_model" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "model" varchar NOT NULL)
query: CREATE TABLE "temporary_ir_device" ("createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "nodeId" integer, "readerDeviceId" integer, "irTypeId" integer, CONSTRAINT "REL_f41f602cc3f82ae81002343601" UNIQUE ("readerDeviceId"), CONSTRAINT "FK_b89b432fe1c70d49c74c83d6c67" FOREIGN KEY ("nodeId") REFERENCES "node" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_f41f602cc3f82ae810023436010" FOREIGN KEY ("readerDeviceId") REFERENCES "node" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_da399010bcb561eacc4b1c83563" FOREIGN KEY ("irTypeId") REFERENCES "ir_device" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)
query: INSERT INTO "temporary_ir_device"("createdAt", "updatedAt", "id", "nodeId", "readerDeviceId", "irTypeId") SELECT "createdAt", "updatedAt", "id", "nodeId", "readerDeviceId", "irTypeId" FROM "ir_device"
query: DROP TABLE "ir_device"
query: ALTER TABLE "temporary_ir_device" RENAME TO "ir_device"
query: CREATE TABLE "temporary_aircon_device_status" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "readerDeviceId" integer, "irDeviceId" integer, "tempCurrenttemperature" integer NOT NULL, "tempSettingtemperature" integer NOT NULL, CONSTRAINT "REL_6a70d5a7ea294ba7efa5ae326d" UNIQUE ("readerDeviceId"), CONSTRAINT "REL_c90ce7ba2ccd5df5a8fd2b2dab" UNIQUE ("irDeviceId"), CONSTRAINT "FK_6a70d5a7ea294ba7efa5ae326d8" FOREIGN KEY ("readerDeviceId") REFERENCES "node" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_c90ce7ba2ccd5df5a8fd2b2dabd" FOREIGN KEY ("irDeviceId") REFERENCES "ir_device" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)
query: INSERT INTO "temporary_aircon_device_status"("id", "readerDeviceId", "irDeviceId", "tempCurrenttemperature", "tempSettingtemperature") SELECT "id", "readerDeviceId", "irDeviceId", "tempCurrenttemperature", "tempSettingtemperature" FROM "aircon_device_status"
query: DROP TABLE "aircon_device_status"
query: ALTER TABLE "temporary_aircon_device_status" RENAME TO "aircon_device_status"
query: CREATE TABLE "temporary_ami_status" ("createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "nodeId" integer, "channel1NameChannelname1" varchar NOT NULL, "channel1NameChannelname2" varchar NOT NULL, "channel1NameChannelname3" varchar NOT NULL, "channel1WattWatt1" integer NOT NULL, "channel1WattWatt2" integer NOT NULL, "channel1WattWatt3" integer NOT NULL, "channel1WattHourWatthour1" integer NOT NULL, "channel1WattHourWatthour2" integer NOT NULL, "channel1WattHourWatthour3" integer NOT NULL, "channel2NameChannelname1" varchar NOT NULL, "channel2NameChannelname2" varchar NOT NULL, "channel2NameChannelname3" varchar NOT NULL, "channel2WattWatt1" integer NOT NULL, "channel2WattWatt2" integer NOT NULL, "channel2WattWatt3" integer NOT NULL, "channel2WattHourWatthour1" integer NOT NULL, "channel2WattHourWatthour2" integer NOT NULL, "channel2WattHourWatthour3" integer NOT NULL, CONSTRAINT "REL_311f085e405c61b6ef447407cf" UNIQUE ("nodeId"), CONSTRAINT "FK_311f085e405c61b6ef447407cf8" FOREIGN KEY ("nodeId") REFERENCES "node" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)
query: INSERT INTO "temporary_ami_status"("createdAt", "updatedAt", "id", "nodeId", "channel1NameChannelname1", "channel1NameChannelname2", "channel1NameChannelname3", "channel1WattWatt1", "channel1WattWatt2", "channel1WattWatt3", "channel1WattHourWatthour1", "channel1WattHourWatthour2", "channel1WattHourWatthour3", "channel2NameChannelname1", "channel2NameChannelname2", "channel2NameChannelname3", "channel2WattWatt1", "channel2WattWatt2", "channel2WattWatt3", "channel2WattHourWatthour1", "channel2WattHourWatthour2", "channel2WattHourWatthour3") SELECT "createdAt", "updatedAt", "id", "nodeId", "channel1NameChannelname1", "channel1NameChannelname2", "channel1NameChannelname3", "channel1WattWatt1", "channel1WattWatt2", "channel1WattWatt3", "channel1WattHourWatthour1", "channel1WattHourWatthour2", "channel1WattHourWatthour3", "channel2NameChannelname1", "channel2NameChannelname2", "channel2NameChannelname3", "channel2WattWatt1", "channel2WattWatt2", "channel2WattWatt3", "channel2WattHourWatthour1", "channel2WattHourWatthour2", "channel2WattHourWatthour3" FROM "ami_status"
query: DROP TABLE "ami_status"
query: ALTER TABLE "temporary_ami_status" RENAME TO "ami_status"
query: COMMIT
query: PRAGMA foreign_keys = ON
